# Generated by Django 4.2.4 on 2023-09-20 05:43

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bankaccounts', '0004_alter_kyc_identity_image_alter_kyc_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=15, max_length=25, prefix='', unique=True)),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('receiver_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sender_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[['failed', 'FAILED'], ['completed', 'COMPLETED'], ['pending', 'PENDING'], ['processing', 'PROCESSING'], ['request_sent', 'REQUEST_SENT'], ['request_processing', 'REQUEST_PROCESSING']], max_length=200)),
                ('transaction_type', models.CharField(choices=[['transfer', 'TRANSFER'], ['withdraw', 'WITHDRAW'], ['refund', 'REFUND'], ['received', 'RECEIVED'], ['request', 'REQUEST'], ['none', 'NONE']], max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField()),
                ('receiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bankaccounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='bankaccounts.account')),
            ],
        ),
    ]
