# Generated by Django 4.2.4 on 2023-10-12 05:30

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_credit_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_card',
            name='number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=12, max_length=16, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='credit_card',
            name='card_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=10, max_length=20, prefix='CRED', unique=True),
        ),
    ]
