# Generated by Django 4.2.4 on 2023-10-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_credit_card_number_alter_credit_card_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_card',
            name='month',
            field=models.CharField(max_length=100),
        ),
    ]
